### ISSUE TITLE
2.9.2 with GF 1.9.15 shows notice on save of a form

### ISSUE THREAD

**Issue by jmslbam** [pronamic/wp-gravityforms-nl#3]
2.9.2 with GF 1.9.15 shows notice on save of a form

```
Notice: Undefined index: gravityforms-nl-forms in /srv/www/typical-tropical/htdocs/wp-includes/class.wp-scripts.php on line 185

Notice: Trying to get property of non-object in /srv/www/typical-tropical/htdocs/wp-includes/class.wp-scripts.php on line 185
```

Don't know why :dancer:

**Comment by remcotolsma** [comment]
I just tried to reproduce this problem, but i don't see any notice on WordPress `4.5`, Gravity Forms `1.9.18.3` and Gravity Forms (nl) `2.9.3` while saving a new Gravity Forms form.

```php
define( 'WP_DEBUG', true );
```
![schermafbeelding 2016-04-14 om 09 37 07](https://cloud.githubusercontent.com/assets/869674/14520392/95aa81ee-0224-11e6-8fac-4eae11e02084.png)
